### PR TITLE
Add many functions e fix

### PR DESCRIPTION
**Pull request by rudacs**
Each group can have a number of columns.

Also updated the example "Grouping"

### CODE REVIEW

**Comment by rudacs** [comment]
If it is a GroupHeaderTemplate, the Key is the group object itself.
In order to facilitate group content binding.

**Comment by rudacs** [comment]
Add Loading Infinite

**Comment by rudacs** [comment]
Add Support to EmptyCell

**Comment by rudacs** [comment]
When adding more than one record to an ObservableCollection use the SmartObservableCollection and AddRange or methods (BatchStart and BatchEnd) to avoid unnecessary processing when adding many items.

**Comment by daniel-luberda** [comment]
Hi @rudacs,

I am really impressed by that PR. Outstanding work! Thanks for your collaboration. It's already merged. I made some small refactorings:

- added obsoleted `DesiredColumnCount` property for compatibility
- renamed some internal classes
- moved some advanced usage scenarios (infinite loading & custom per cell column count) to separate examples pages) for clarity

That's a ton of some good work :) 👍 @rudacs Cheers

**Pull request merged**
